### ISSUE TITLE
query: does pain socket work in browser? not ws

### ISSUE THREAD

**Issue by 0xMALVEE** [bashlund/pocket-sockets#22]
![image](https://github.com/bashlund/pocket-sockets/assets/35369563/d13ffa24-6a1e-4531-a3bf-9281a62948fa)
query: does pain socket work in browser? not ws

**Comment by bashlund** [comment]
Hi @0xMALVEE,

no, browsers only support WebSockets, not plain TCP sockets.

edit: meaning you will need to use WebSockets also on server side for the browser to be able to connect.
